spring.application.name=tea-social
spring.datasource.url=jdbc:postgresql://localhost:5432/teasocial
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# ????????? Hibernate
# update ? ????????????? ???????/?????? ??????? ? ?? ??? ???????
spring.jpa.hibernate.ddl-auto=create-drop   
# ?????????? SQL ??????? ? ???????
spring.jpa.show-sql=true

app.jwt-secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciB0ZWEtc29jaWFsIGFwcGxpY2F0aW9uIDI1NiBiaXRzIGxvbmc=
app.jwt-expiration=86400000